# Generated by Django 4.0.6 on 2022-07-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('writtendate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('group', models.CharField(max_length=10)),
                ('birthday', models.DateField(null=True)),
            ],
        ),
    ]
