# Generated by Django 4.0.6 on 2022-07-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0002_remove_mypost_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='enddate',
            field=models.DateField(null=True),
        ),
    ]
