# Generated by Django 4.0.6 on 2022-07-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0003_alter_mypost_enddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='group',
        ),
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mypost',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
