# Generated by Django 4.0.6 on 2022-07-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0004_remove_myuser_group_myuser_age_myuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
