# Generated by Django 4.0.6 on 2022-07-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0006_alter_myuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, default='정보없음', max_length=13, null=True),
        ),
    ]
